name: movies_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


# NOTE: dependencies
  http: ^1.0.0
  cupertino_icons: ^1.0.2
  card_swiper: ^2.0.4
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# NOTE: lints
  flutter_lints: ^2.0.0

# NOTE: packages
flutter:
  uses-material-design: true

# NOTE: assets
  assets:
    - assets/
    - assets/images/
    - assets/videos/
  #   - images/a_dot_ham.jpeg

# NOTE: fonts

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
